en:
  languageCode: en-us
  contentDir: content/en
it:
  languageCode: it-it
  contentDir: content/it
  title: Sito FP
  params:
    description: Sito personale di Franco Pasut
    date_format: 2/1/2006
  menu:
    main:
      - name: Domus
        url: '#about'
        weight: 1
      - name: Ultimi articoli
        url: '#posts'
        weight: 2
      - name: Argomenti
        url: '#tags'
        weight: 3
      - name: Per contattarmi
        url: '#contact'
        weight: 4
